allcountryabbrev = ['CAF','BDI','AGO','COD','BWA','COG','CIV','BFA','DZA','ETH','EGY','GIN','ERI','GNB','GHA','GNQ','LBY','LBR','KEN','MAR','CMR','BEN','MOZ','MLI','DJI','MWI','NAM','MRT','GAB','SAH','NGA','GMB','SLE','SEN','RWA','SOM','SDS','TUN','TCD','UGA','TZA','ZWE','LSO','ZMB','AFG','MDG','ARM','ARE','NER','AZE','SDN','BRN','CHN','SWZ','CYN','CYP','GEO','TGO','SOL','IDN','IND','IRN','ISR','JOR','ZAF','KHM','KOR','KAZ','BTN','BGD','IRQ','JPN','MYS','NPL','LKA','OMN','KGZ','MMR','PHL','KWT','LAO','SAU','LBN','SYR','MNG','QAT','TLS','PAK','TUR','PRK','ARG','BOL','TWN','BRA','CHL','VNM','TKM','COL','ECU','FLK','GUY','YEM','PER','SUR','URY','PRY','VEN','THA','BHS','BLZ','CAN','CRI','CUB','DOM','GTM','GRL','HND','HTI','JAM','TJK','MEX','UZB','PAN','NIC','PRI','SLV','TTO','USA','BGR','BLR','BIH','DEU','CZE','ALB','BEL','CHE','ESP','AUT','DNK','FRA','FIN','GBR','PSX','EST','GRC','HRV','IRL','KOS','ISL','HUN','LUX','ITA','LTU','LVA','NLD','MDA','NOR','PRT','MKD','MNE','ROU','POL','SRB','SVK','UKR','SVN','AUS','SWE','RUS','FJI','NCL','NZL','PNG','SLB','VUT']
allcountrynames = ['Central African Republic', 'Burundi', 'Angola', 'Democratic Republic of the Congo', 'Botswana', 'Republic of Congo', 'Ivory Coast', 'Burkina Faso', 'Algeria', 'Ethiopia', 'Egypt', 'Guinea', 'Eritrea', 'Guinea Bissau', 'Ghana', 'Equatorial Guinea', 'Libya', 'Liberia', 'Kenya', 'Morocco', 'Cameroon', 'Benin', 'Mozambique', 'Mali', 'Djibouti', 'Malawi', 'Namibia', 'Mauritania', 'Gabon', 'Western Sahara', 'Nigeria', 'Gambia', 'Sierra Leone', 'Senegal', 'Rwanda', 'Somalia', 'South Sudan', 'Tunisia', 'Chad', 'Uganda', 'United Republic of Tanzania', 'Zimbabwe', 'Lesotho', 'Zambia', 'Afghanistan', 'Madagascar', 'Armenia', 'United Arab Emirates', 'Niger', 'Azerbaijan', 'Sudan', 'Brunei', 'China', 'Swaziland', 'Northern Cyprus', 'Cyprus', 'Georgia', 'Togo', 'Somaliland', 'Indonesia', 'India', 'Iran', 'Israel', 'Jordan', 'South Africa', 'Cambodia', 'South Korea', 'Kazakhstan', 'Bhutan', 'Bangladesh', 'Iraq', 'Japan', 'Malaysia', 'Nepal', 'Sri Lanka', 'Oman', 'Kyrgyzstan', 'Myanmar', 'Philippines', 'Kuwait', 'Laos', 'Saudi Arabia', 'Lebanon', 'Syria', 'Mongolia', 'Qatar', 'East Timor', 'Pakistan', 'Turkey', 'North Korea', 'Argentina', 'Bolivia', 'Taiwan', 'Brazil', 'Chile', 'Vietnam', 'Turkmenistan', 'Colombia', 'Ecuador', 'Falkland Islands', 'Guyana', 'Yemen', 'Peru', 'Suriname', 'Uruguay', 'Paraguay', 'Venezuela', 'Thailand', 'The Bahamas', 'Belize', 'Canada', 'Costa Rica', 'Cuba', 'Dominican Republic', 'Guatemala', 'Greenland', 'Honduras', 'Haiti', 'Jamaica', 'Tajikistan', 'Mexico', 'Uzbekistan', 'Panama', 'Nicaragua', 'Puerto Rico', 'El Salvador', 'Trinidad and Tobago', 'United States of America', 'Bulgaria', 'Belarus', 'Bosnia and Herzegovina', 'Germany', 'Czech Republic', 'Albania', 'Belgium', 'Switzerland', 'Spain', 'Austria', 'Denmark', 'France', 'Finland', 'United Kingdom', 'Palestine', 'Estonia', 'Greece', 'Croatia', 'Ireland', 'Kosovo', 'Iceland', 'Hungary', 'Luxembourg', 'Italy', 'Lithuania', 'Latvia', 'Netherlands', 'Moldova', 'Norway', 'Portugal', 'Macedonia', 'Montenegro', 'Romania', 'Poland', 'Republic of Serbia', 'Slovakia', 'Ukraine', 'Slovenia', 'Australia', 'Sweden', 'Russia', 'Fiji', 'New Caledonia', 'New Zealand', 'Papua New Guinea', 'Solomon Islands', 'Vanuatu']
oly_abbrev = ['HUN', 'AUT', 'GRE', 'USA', 'GER', 'GBR', 'FRA', 'AUS', 'DEN', 'SUI', 'ZZX', 'NED', 'BEL', 'IND', 'CAN', 'BOH', 'SWE', 'NOR', 'ESP', 'ITA', 'CUB', 'ANZ', 'RSA', 'FIN', 'RU1', 'EST', 'TCH', 'NZL', 'BRA', 'JPN', 'LUX', 'ARG', 'POL', 'POR', 'URU', 'YUG', 'ROU', 'HAI', 'EGY', 'PHI', 'IRL', 'CHI', 'LAT', 'MEX', 'TUR', 'PAN', 'JAM', 'SRI', 'KOR', 'PUR', 'PER', 'IRI', 'TRI', 'URS', 'VEN', 'BUL', 'LIB', 'EUA', 'ISL', 'PAK', 'BAH', 'BWI', 'TPE', 'ETH', 'MAR', 'GHA', 'IRQ', 'SIN', 'TUN', 'KEN', 'NGR', 'GDR', 'FRG', 'UGA', 'CMR', 'MGL', 'PRK', 'COL', 'NIG', 'THA', 'BER', 'TAN', 'GUY', 'ZIM', 'CHN', 'CIV', 'ZAM', 'DOM', 'ALG', 'SYR', 'SUR', 'CRC', 'INA', 'SEN', 'DJI', 'AHO', 'ISV', 'EUN', 'NAM', 'QAT', 'LTU', 'MAS', 'CRO', 'ISR', 'SLO', 'IOP', 'RUS', 'UKR', 'ECU', 'BDI', 'MOZ', 'CZE', 'BLR', 'TGA', 'KAZ', 'UZB', 'SVK', 'MDA', 'GEO', 'HKG', 'ARM', 'AZE', 'BAR', 'KSA', 'KGZ', 'KUW', 'VIE', 'MKD', 'SCG', 'ERI', 'PAR', 'UAE', 'SRB', 'SUD', 'MRI', 'TOG', 'TJK', 'AFG', 'BRN', 'GUA', 'GRN', 'TTO', 'BOT', 'MNE', 'CYP', 'SGP', 'GAB']
matched_abbrev = [['BOL','BOL'],['TKM','TKM'],['YEM','YEM'],['SOL','SLB'],['TLS','TLS'],['PLE','PSX'],['BIH','BIH'],['ALB','ALB'],['ESA','SLV'],['BHU','BTN'],['BAN','BGD'],['OMA','OMN'],['LAO','LAO'],['CAM','KHM'],['GEQ','GNQ'],['GBS','GNB'],['PNG','PNG'],['JOR','JOR'],['GUI','GIN'],['MTN','MRT'],['LAT','LVA'],['TOG','TGO'],['TPE','TWN'],['BAH','BHS'],['PUR','PRI'],['PHI','PHL'],['RU1','RUS'],['URS','RUS'],['TCH','CZE'],['SCG','SRB'],['YUG','SRB'],['EUA','DEU'],['EUN','DEU'],['FRG','DEU'],['GDR','DEU'],['BWI','JAM'],['ANZ','AUS'],['KSA','SAU'],['KUW','KWT'],['NEP','NPL'],['MGL','MNG'],['MAD','MDG'],['LES','LSO'],['VIE','VNM'],['VAN','VUT'],['LIB','LBN'],['NCA','NIC'],['BIZ','BLZ'],['SLO','SVN'],['SRI','LKA'],['HON','HND'],['MYA','MMR'],['MAS','MYS'],['INA','IDN'],['IRI','IRN'],['FIJ','FJI'],['CRO','HRV'],['GUA','GTM'],['HAI','HTI'],['URU','URY'],['SUD','SDN'],['SWZ','SWZ'],['NIG','NER'],['NGR','NGA'],['GAM','GMB'],['SLE','SLE'],['SOM','SOM'],['CHA','TCD'],['CHI','CHL'],['CRC','CRI'],['BUR','BFA'],['BUL','BGR'],['BEN','BEN'],['ZIM','ZWE'],['ZAM','ZMB'],['UAE','ARE'],['SUI','CHE'],['RSA','ZAF'],['RWA','RWA'],['PAR','PRY'],['POR','PRT'],['BOH','CZE'],['LBA','LBY'],['LBR','LBR'],['MLI','MLI'],['MAW','MWI'],['ALG','DZA'],['CAF','CAF'],['ANG','AGO'],['BOT','BWA'],['COD','COD'],['CGO','COG'],['TAN','TZA'],['NED','NLD'],['GRE','GRC'],['DEN','DNK'],['GER','DEU'],['HUN', 'HUN'], ['AUT', 'AUT'], ['USA', 'USA'], ['GBR', 'GBR'], ['FRA', 'FRA'], ['AUS', 'AUS'], ['BEL', 'BEL'], ['IND', 'IND'], ['CAN', 'CAN'], ['SWE', 'SWE'], ['NOR', 'NOR'], ['ESP', 'ESP'], ['ITA', 'ITA'], ['CUB', 'CUB'], ['FIN', 'FIN'], ['EST', 'EST'], ['NZL', 'NZL'], ['BRA', 'BRA'], ['JPN', 'JPN'], ['LUX', 'LUX'], ['ARG', 'ARG'], ['POL', 'POL'], ['ROU', 'ROU'], ['EGY', 'EGY'], ['IRL', 'IRL'], ['MEX', 'MEX'], ['TUR', 'TUR'], ['PAN', 'PAN'], ['JAM', 'JAM'], ['KOR', 'KOR'], ['PER', 'PER'], ['VEN', 'VEN'], ['ISL', 'ISL'], ['PAK', 'PAK'], ['ETH', 'ETH'], ['MAR', 'MAR'], ['GHA', 'GHA'], ['IRQ', 'IRQ'], ['TUN', 'TUN'], ['KEN', 'KEN'], ['UGA', 'UGA'], ['CMR', 'CMR'], ['PRK', 'PRK'], ['COL', 'COL'], ['THA', 'THA'], ['GUY', 'GUY'], ['CHN', 'CHN'], ['CIV', 'CIV'], ['DOM', 'DOM'], ['SYR', 'SYR'], ['SUR', 'SUR'], ['SEN', 'SEN'], ['DJI', 'DJI'], ['NAM', 'NAM'], ['QAT', 'QAT'], ['LTU', 'LTU'], ['ISR', 'ISR'], ['RUS', 'RUS'], ['UKR', 'UKR'], ['ECU', 'ECU'], ['BDI', 'BDI'], ['MOZ', 'MOZ'], ['CZE', 'CZE'], ['BLR', 'BLR'], ['KAZ', 'KAZ'], ['UZB', 'UZB'], ['SVK', 'SVK'], ['MDA', 'MDA'], ['GEO', 'GEO'], ['ARM', 'ARM'], ['AZE', 'AZE'], ['KGZ', 'KGZ'], ['MKD', 'MKD'], ['ERI', 'ERI'], ['SRB', 'SRB'], ['TJK', 'TJK'], ['AFG', 'AFG'], ['BRN', 'BRN'], ['TTO', 'TTO'], ['MNE', 'MNE'], ['CYP', 'CYP'], ['GAB', 'GAB']]

missingca = []
missingoa = []

for i in oly_abbrev:
	alreadymatched = False
	for ii in matched_abbrev:
		if i==ii[0]:
			alreadymatched = True
	if not alreadymatched:
		if i not in allcountryabbrev:
			missingoa.append(i)
		else:
			matched_abbrev.append([i,i])

for idx,i in enumerate(allcountryabbrev):
	alreadymatched = False
	for ii in matched_abbrev:
		if i==ii[1]:
			alreadymatched = True
	if not alreadymatched:
		if i not in oly_abbrev:
			missingca.append([i,allcountrynames[idx]])


